# Generated by Django 4.1.1 on 2022-09-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
