# Generated by Django 4.1.1 on 2022-10-09 19:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0019_customerorders_orderdeliverystatus_product_reviews_and_more'),
        ('Grocery', '0002_whishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Whishlist',
            new_name='Wishlist',
        ),
    ]
