# Generated by Django 4.1.1 on 2022-09-17 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery', '0002_alter_cart_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
