# Generated by Django 4.1.1 on 2022-09-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery', '0005_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
