# Generated by Django 4.1.1 on 2022-09-18 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery', '0009_alter_cart_cart_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
