# Generated by Django 4.1.1 on 2022-09-28 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_productattribute_color_and_more'),
        ('Grocery', '0010_delete_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cart_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='store.productattribute'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='product_qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
