# Generated by Django 4.1.1 on 2022-09-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery', '0012_rename_created_at_cart_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='Product_attribute',
        ),
    ]
