# Generated by Django 4.1.1 on 2022-09-28 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery', '0013_remove_cartitem_product_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='Cart',
        ),
    ]
