# Generated by Django 4.1.1 on 2022-10-08 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery', '0014_remove_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='Cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Grocery.cart'),
        ),
    ]
