# Generated by Django 4.1.1 on 2022-10-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery', '0003_rename_whishlist_wishlist'),
        ('Grocery', '0015_cartitem_cart'),
    ]

    operations = [
    ]
