# Generated by Django 4.1.1 on 2022-10-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery', '0016_remove_cart_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
