# Generated by Django 4.1.1 on 2022-09-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/products'),
        ),
    ]
