# Generated by Django 4.1.1 on 2022-09-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_product_color_remove_product_storage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name_plural': '7. ProductAttributes'},
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/products'),
        ),
    ]
