# Generated by Django 4.1.1 on 2022-09-26 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_rename_size_storage'),
        ('store', '0012_remove_orderdeliverystatus_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.color'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.storage'),
        ),
    ]
