# Generated by Django 4.1.1 on 2022-09-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_productattribute_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
