# Generated by Django 4.1.1 on 2022-09-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productattribute_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
