# Generated by Django 4.1.1 on 2022-10-13 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_customerorders_orderdeliverystatus_product_reviews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdeliverystatus',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='product_reviews',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='product_reviews',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='productmedia',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='productreviewvoting',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='productreviewvoting',
            name='user_id_voting',
        ),
        migrations.RemoveField(
            model_name='producttransaction',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='productvarientitems',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='productvarientitems',
            name='product_varient_id',
        ),
        migrations.DeleteModel(
            name='CustomerOrders',
        ),
        migrations.DeleteModel(
            name='OrderDeliveryStatus',
        ),
        migrations.DeleteModel(
            name='Product_Reviews',
        ),
        migrations.DeleteModel(
            name='ProductMedia',
        ),
        migrations.DeleteModel(
            name='ProductReviewVoting',
        ),
        migrations.DeleteModel(
            name='ProductTransaction',
        ),
        migrations.DeleteModel(
            name='ProductVarient',
        ),
        migrations.DeleteModel(
            name='ProductVarientItems',
        ),
    ]
