# Generated by Django 3.2.16 on 2022-10-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20221016_1856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavourateProducts',
        ),
    ]
