# Generated by Django 3.2.16 on 2022-10-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_homebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
