# Generated by Django 3.2.16 on 2022-10-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_wishlist_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
