# Generated by Django 3.2.16 on 2022-10-28 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_wishlist_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='count',
        ),
    ]
