# Generated by Django 3.2.16 on 2023-03-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_remove_wishlist_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
