# Generated by Django 4.1.1 on 2022-09-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=355)),
                ('email', models.CharField(max_length=355)),
                ('bio', models.TextField(max_length=2000)),
            ],
        ),
    ]
