# Generated by Django 4.1.1 on 2022-09-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
