# Generated by Django 4.1.1 on 2022-09-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_subcategorys_product_subcategory'),
        ('category', '0004_brand_color_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='size',
            new_name='Storage',
        ),
    ]
