# Generated by Django 4.1.1 on 2022-10-08 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_customerorders_orderdeliverystatus_product_reviews_and_more'),
        ('category', '0005_rename_size_storage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='color',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
