# Generated by Django 4.1.1 on 2022-09-28 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_productattribute_quantity'),
        ('CartApp', '0003_alter_cart_product_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_attribute',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.productattribute'),
            preserve_default=False,
        ),
    ]
