# Generated by Django 4.1.1 on 2022-09-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
