# Generated by Django 4.1.1 on 2022-09-19 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_product_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_total',
        ),
    ]
