# Generated by Django 4.1.1 on 2022-10-10 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_message_order_tracking_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
