# Generated by Django 4.1.1 on 2022-10-10 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_postal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='postal_code',
            new_name='post_code',
        ),
    ]
